// <auto-generated />
using AchuBan_ECom.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AchuBan_ECom.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251024134328_seed-Category")]
    partial class seedCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AchuBan_ECom.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("displayOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Action Movies",
                            Name = "Action",
                            displayOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Comedy Movies",
                            Name = "Comedy",
                            displayOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Drama Movies",
                            Name = "Drama",
                            displayOrder = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
