// <auto-generated />
using AchuBan_ECom.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AchuBan_ECom.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251027090416_ForeignKeyCatId")]
    partial class ForeignKeyCatId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AchuBan_ECom.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("displayOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Action Movies",
                            Name = "Action",
                            displayOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Comedy Movies",
                            Name = "Comedy",
                            displayOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Drama Movies",
                            Name = "Drama",
                            displayOrder = 3
                        });
                });

            modelBuilder.Entity("AchuBan_ECom.Models.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ListPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price100")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price50")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Mr. Max seed",
                            CategoryId = 1,
                            Description = "Description 1",
                            ISBN = "ISBN-123",
                            ListPrice = 10.00m,
                            Name = "Product 1",
                            Price100 = 8.00m,
                            Price50 = 9.00m
                        },
                        new
                        {
                            Id = 2,
                            Author = "Mr. Seed 123",
                            CategoryId = 2,
                            Description = "Description 2",
                            ISBN = "ISBN-456",
                            ListPrice = 20.00m,
                            Name = "Product 2",
                            Price100 = 16.00m,
                            Price50 = 18.00m
                        },
                        new
                        {
                            Id = 3,
                            Author = "Mr. Mooc seed",
                            CategoryId = 3,
                            Description = "Description 3",
                            ISBN = "ISBN-789",
                            ListPrice = 30.00m,
                            Name = "Product 3",
                            Price100 = 24.00m,
                            Price50 = 27.00m
                        },
                        new
                        {
                            Id = 4,
                            Author = "Mr. Mussie seed",
                            CategoryId = 1,
                            Description = "Description 4",
                            ISBN = "ISBN-101",
                            ListPrice = 40.00m,
                            Name = "Product 4",
                            Price100 = 32.00m,
                            Price50 = 36.00m
                        },
                        new
                        {
                            Id = 5,
                            Author = "Mr. Max seed",
                            CategoryId = 2,
                            Description = "Description 5",
                            ISBN = "ISBN-102",
                            ListPrice = 50.00m,
                            Name = "Product 5",
                            Price100 = 40.00m,
                            Price50 = 45.00m
                        },
                        new
                        {
                            Id = 6,
                            Author = "Mr. Haile seed",
                            CategoryId = 3,
                            Description = "Description 6",
                            ISBN = "ISBN-103",
                            ListPrice = 60.00m,
                            Name = "Product 6",
                            Price100 = 48.00m,
                            Price50 = 54.00m
                        },
                        new
                        {
                            Id = 7,
                            Author = "Mr. Max seed",
                            CategoryId = 1,
                            Description = "Description 7",
                            ISBN = "ISBN-104",
                            ListPrice = 70.00m,
                            Name = "Product 7",
                            Price100 = 56.00m,
                            Price50 = 63.00m
                        },
                        new
                        {
                            Id = 8,
                            Author = "Mr. Assin seed",
                            CategoryId = 2,
                            Description = "Description 8",
                            ISBN = "ISBN-105",
                            ListPrice = 80.00m,
                            Name = "Product 8",
                            Price100 = 64.00m,
                            Price50 = 72.00m
                        });
                });

            modelBuilder.Entity("AchuBan_ECom.Models.Models.Product", b =>
                {
                    b.HasOne("AchuBan_ECom.Models.Category", "category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });
#pragma warning restore 612, 618
        }
    }
}
